option(SDL_SHARED "" OFF)
option(SDL_STATIC "" ON)
option(SDL_TEST   "" OFF)
##option(SDL_FORCE_STATIC_VCRT "Force /MT for static VC runtimes" OFF)
option(SDL3_DISABLE_INSTALL    "" ON)
option(SDL3_DISABLE_UNINSTALL  "" ON)
add_subdirectory("${DEPS_DIRECTORY}/SDL" SDL)
include_directories("${DEPS_DIRECTORY}/SDL/include")
set_target_properties("SDL3-static" PROPERTIES FOLDER "libs")
set(SDL3_LIBRARIES "SDL3-static")